"""fund AUM snapshots (N-PORT)

Revision ID: 00f725b1dccc
Revises: cb731d1c2a2d
Create Date: 2026-09-13 21:57:48.155730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00f725b1dccc'
down_revision: Union[str, Sequence[str], None] = 'cb731d1c2a2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('series_name', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('fund_aum_snapshots',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('fund_entity_id', sa.Uuid(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('total_assets_usd', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('total_liabilities_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('net_assets_usd', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('net_assets_change_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('filing_form_type', sa.String(length=16), nullable=True),
    sa.Column('filing_accession', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['fund_entity_id'], ['funds.entity_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_fund_aum_snapshots_fund_entity_id'), 'fund_aum_snapshots', ['fund_entity_id'], unique=False)
    op.create_index(op.f('ix_fund_aum_snapshots_period_end'), 'fund_aum_snapshots', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fund_aum_snapshots_period_end'), table_name='fund_aum_snapshots')
    op.drop_index(op.f('ix_fund_aum_snapshots_fund_entity_id'), table_name='fund_aum_snapshots')
    op.drop_table('fund_aum_snapshots')
    op.drop_table('funds')
    # ### end Alembic commands ###
