"""Phase 14: Cboe volatility index levels

Revision ID: 079b7e248177
Revises: 0a3e163618a4
Create Date: 2026-09-14 02:44:32.686970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '079b7e248177'
down_revision: Union[str, Sequence[str], None] = '0a3e163618a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volatility_index_levels',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('index_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', name='uq_volatility_index_level')
    )
    op.create_index(op.f('ix_volatility_index_levels_index_code'), 'volatility_index_levels', ['index_code'], unique=False)
    op.create_index(op.f('ix_volatility_index_levels_trade_date'), 'volatility_index_levels', ['trade_date'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed, same stale VARCHAR-vs-Enum
    # noise as every prior migration since 8224e63bf9e8. No new
    # IdentifierType value is added in this phase.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_volatility_index_levels_trade_date'), table_name='volatility_index_levels')
    op.drop_index(op.f('ix_volatility_index_levels_index_code'), table_name='volatility_index_levels')
    op.drop_table('volatility_index_levels')
    # ### end Alembic commands ###
