"""Phase 14: M&A corporate action disclosures (SEC 8-K Item 2.01)

Revision ID: 0a3e163618a4
Revises: b411ead20d94
Create Date: 2026-09-14 02:35:18.482627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3e163618a4'
down_revision: Union[str, Sequence[str], None] = 'b411ead20d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action_disclosures',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('item_codes', sa.String(length=64), nullable=False),
    sa.Column('filing_form_type', sa.String(length=16), nullable=False),
    sa.Column('filing_accession', sa.String(length=32), nullable=False),
    sa.Column('primary_document_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_corporate_action_disclosures_company_entity_id'), 'corporate_action_disclosures', ['company_entity_id'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed, same stale VARCHAR-vs-Enum
    # noise as every prior migration since 8224e63bf9e8. No new
    # IdentifierType value is added in this phase.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_action_disclosures_company_entity_id'), table_name='corporate_action_disclosures')
    op.drop_table('corporate_action_disclosures')
    # ### end Alembic commands ###
