"""raw_data_reference becomes an indexed unique idempotency key

Revision ID: 0f32fe86fe38
Revises: 2b27bffbf825
Create Date: 2026-09-13 19:50:15.131971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f32fe86fe38'
down_revision: Union[str, Sequence[str], None] = '2b27bffbf825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # batch mode: SQLite can't ALTER COLUMN TYPE or add a constraint in
    # place, so this is rewritten as a table rebuild there; on Postgres it
    # collapses to the plain ALTER TABLE the autogenerated version used.
    with op.batch_alter_table("events") as batch_op:
        batch_op.alter_column(
            "raw_data_reference",
            existing_type=sa.TEXT(),
            type_=sa.String(length=512),
            existing_nullable=True,
        )
        batch_op.create_unique_constraint("uq_events_raw_data_reference", ["raw_data_reference"])


def downgrade() -> None:
    with op.batch_alter_table("events") as batch_op:
        batch_op.drop_constraint("uq_events_raw_data_reference", type_="unique")
        batch_op.alter_column(
            "raw_data_reference",
            existing_type=sa.String(length=512),
            type_=sa.TEXT(),
            existing_nullable=True,
        )
