"""initial schema: entities, sources, events, insider transactions

Revision ID: 2b27bffbf825
Revises: 
Create Date: 2026-09-13 19:24:37.157996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b27bffbf825'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('entity_type', sa.Enum('COMPANY', 'PERSON', 'INSTITUTION', 'FUND', 'ETF', 'TRUST', 'GOVERNMENT_ENTITY', 'ACTIVIST', 'CRYPTO_WALLET', 'CRYPTO_PROTOCOL', 'EXCHANGE', 'MARKET_MAKER', 'FOUNDATION', 'SUPPLIER', 'CUSTOMER', 'COMPETITOR', 'OTHER', name='entity_type'), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('tier', sa.Enum('A_OFFICIAL', 'B_LICENSED', 'C_PUBLICATION', 'D_UNVERIFIED', name='source_tier'), nullable=False),
    sa.Column('base_url', sa.String(length=1024), nullable=True),
    sa.Column('license_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('companies',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('documents',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=256), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('raw_storage_ref', sa.String(length=1024), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_external_id'), 'documents', ['external_id'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('entity_identifiers',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('identifier_type', sa.Enum('TICKER', 'CUSIP', 'ISIN', 'CIK', 'LEI', 'EXCHANGE_CODE', 'WALLET_ADDRESS', 'ALIAS', 'FUND_ID', name='identifier_type'), nullable=False),
    sa.Column('identifier_value', sa.String(length=128), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier_type', 'identifier_value', 'exchange', 'valid_from', name='uq_identifier_scope')
    )
    op.create_index(op.f('ix_entity_identifiers_entity_id'), 'entity_identifiers', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_identifier_type'), 'entity_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_entity_identifiers_identifier_value'), 'entity_identifiers', ['identifier_value'], unique=False)
    op.create_table('people',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('events',
    sa.Column('event_type', sa.Enum('INSIDER_PURCHASE', 'INSIDER_SALE', 'INSTITUTIONAL_POSITION_CHANGE', 'ACTIVIST_STAKE', 'MAJOR_HOLDER_CHANGE', 'ETF_FLOW', 'SHARE_BUYBACK', 'SECONDARY_OFFERING', 'INSIDER_COMPENSATION', 'EARNINGS', 'GUIDANCE_CHANGE', 'ESTIMATE_REVISION', 'ANALYST_RATING_CHANGE', 'M_AND_A', 'SPINOFF', 'DEBT_ISSUANCE', 'CAPITAL_RAISE', 'CONTRACT_AWARD', 'PRODUCT_LAUNCH', 'REGULATORY_EVENT', 'CLINICAL_TRIAL_EVENT', 'PATENT_EVENT', 'CRYPTO_TRANSFER', 'WHALE_ACCUMULATION', 'EXCHANGE_FLOW', 'TOKEN_UNLOCK', 'TREASURY_MOVEMENT', name='event_type'), nullable=False),
    sa.Column('primary_entity_id', sa.Uuid(), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('announcement_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publication_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_data_reference', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_confidence_range'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_time'), 'events', ['event_time'], unique=False)
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_primary_entity_id'), 'events', ['primary_entity_id'], unique=False)
    op.create_index(op.f('ix_events_publication_time'), 'events', ['publication_time'], unique=False)
    op.create_table('person_company_roles',
    sa.Column('person_entity_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('role_title', sa.String(length=256), nullable=True),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_ten_percent_owner', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['person_entity_id'], ['people.entity_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_company_roles_company_entity_id'), 'person_company_roles', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_person_company_roles_person_entity_id'), 'person_company_roles', ['person_entity_id'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('insider_entity_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_type', sa.Enum('OPEN_MARKET_PURCHASE', 'OPEN_MARKET_SALE', 'OPTION_EXERCISE', 'TAX_WITHHOLDING', 'GIFT', 'COMPENSATION_AWARD', 'AUTOMATIC_10B5_1', 'CONVERSION', 'TRANSFER', 'OTHER', name='insider_transaction_type'), nullable=False),
    sa.Column('shares_transacted', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('price_per_share', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('shares_owned_after', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('is_10b5_1_plan', sa.Boolean(), nullable=False),
    sa.Column('filing_form_type', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['insider_entity_id'], ['people.entity_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_insider_transactions_company_entity_id'), 'insider_transactions', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_insider_transactions_insider_entity_id'), 'insider_transactions', ['insider_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insider_transactions_insider_entity_id'), table_name='insider_transactions')
    op.drop_index(op.f('ix_insider_transactions_company_entity_id'), table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_person_company_roles_person_entity_id'), table_name='person_company_roles')
    op.drop_index(op.f('ix_person_company_roles_company_entity_id'), table_name='person_company_roles')
    op.drop_table('person_company_roles')
    op.drop_index(op.f('ix_events_publication_time'), table_name='events')
    op.drop_index(op.f('ix_events_primary_entity_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_index(op.f('ix_events_event_time'), table_name='events')
    op.drop_table('events')
    op.drop_table('people')
    op.drop_index(op.f('ix_entity_identifiers_identifier_value'), table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_identifier_type'), table_name='entity_identifiers')
    op.drop_index(op.f('ix_entity_identifiers_entity_id'), table_name='entity_identifiers')
    op.drop_table('entity_identifiers')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_external_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_table('companies')
    op.drop_table('sources')
    op.drop_table('entities')
    # ### end Alembic commands ###
