"""beneficial ownership disclosures (13D/13G)

Revision ID: 39445addec0b
Revises: 4ed276abf946
Create Date: 2026-09-13 20:42:23.711294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39445addec0b'
down_revision: Union[str, Sequence[str], None] = '4ed276abf946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficial_ownership_disclosures',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('filer_entity_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_type', sa.Enum('SCHEDULE_13D', 'SCHEDULE_13G', name='schedule_type'), nullable=False),
    sa.Column('filer_type_code', sa.String(length=8), nullable=True),
    sa.Column('shares_beneficially_owned', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('percent_of_class', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('sole_voting_power', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('shared_voting_power', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('sole_dispositive_power', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('shared_dispositive_power', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('stated_purpose', sa.Text(), nullable=True),
    sa.Column('is_joint_filing', sa.Boolean(), nullable=False),
    sa.Column('filing_form_type', sa.String(length=24), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['filer_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_beneficial_ownership_disclosures_company_entity_id'), 'beneficial_ownership_disclosures', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_beneficial_ownership_disclosures_filer_entity_id'), 'beneficial_ownership_disclosures', ['filer_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beneficial_ownership_disclosures_filer_entity_id'), table_name='beneficial_ownership_disclosures')
    op.drop_index(op.f('ix_beneficial_ownership_disclosures_company_entity_id'), table_name='beneficial_ownership_disclosures')
    op.drop_table('beneficial_ownership_disclosures')
    # ### end Alembic commands ###
