"""institutional managers and holdings (13F)

Revision ID: 4ed276abf946
Revises: 0f32fe86fe38
Create Date: 2026-09-13 20:08:36.435992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed276abf946'
down_revision: Union[str, Sequence[str], None] = '0f32fe86fe38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutional_managers',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('manager_type', sa.Enum('LONG_TERM_ASSET_MANAGER', 'INDEX_MANAGER', 'HEDGE_FUND', 'ACTIVIST', 'PENSION', 'SOVEREIGN_WEALTH_FUND', 'FAMILY_OFFICE', 'QUANTITATIVE_FUND', 'VENTURE_FUND', 'PRIVATE_EQUITY', 'STRATEGIC_CORPORATE_INVESTOR', 'OTHER', name='institutional_manager_type'), nullable=False),
    sa.Column('form13f_file_number', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('entity_id')
    )
    op.create_table('institutional_holdings',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('institution_entity_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('period_of_report', sa.Date(), nullable=False),
    sa.Column('shares_held', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('market_value_usd', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('shares_change', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('position_status', sa.Enum('NEW', 'INCREASED', 'DECREASED', 'UNCHANGED', 'EXITED', name='institutional_position_status'), nullable=False),
    sa.Column('filing_form_type', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['institution_entity_id'], ['institutional_managers.entity_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_institutional_holdings_company_entity_id'), 'institutional_holdings', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_institutional_holdings_institution_entity_id'), 'institutional_holdings', ['institution_entity_id'], unique=False)
    op.create_index(op.f('ix_institutional_holdings_period_of_report'), 'institutional_holdings', ['period_of_report'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_institutional_holdings_period_of_report'), table_name='institutional_holdings')
    op.drop_index(op.f('ix_institutional_holdings_institution_entity_id'), table_name='institutional_holdings')
    op.drop_index(op.f('ix_institutional_holdings_company_entity_id'), table_name='institutional_holdings')
    op.drop_table('institutional_holdings')
    op.drop_table('institutional_managers')
    # ### end Alembic commands ###
