"""capital allocation facts + new event types

Revision ID: 60f668c9c433
Revises: 39445addec0b
Create Date: 2026-09-13 20:58:51.747609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60f668c9c433'
down_revision: Union[str, Sequence[str], None] = '39445addec0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # event_type gains two values (DEBT_REPAYMENT, DIVIDEND_PAYMENT) for Phase 7's
    # capital-allocation facts. Only Postgres needs anything done here: our
    # capint.models.event.Event.event_type column uses plain sa.Enum(...) with
    # its default create_constraint=False, so on SQLite (no native enum support)
    # it's a bare VARCHAR with no DB-level restriction to widen — the enum is
    # enforced only at the SQLAlchemy/Python layer there. Postgres, which does
    # have a native enum type, needs the type itself widened.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'DEBT_REPAYMENT'")
        op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'DIVIDEND_PAYMENT'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_allocation_facts',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('xbrl_concept', sa.String(length=128), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('filing_form_type', sa.String(length=16), nullable=True),
    sa.Column('filing_accession', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_capital_allocation_facts_company_entity_id'), 'capital_allocation_facts', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_capital_allocation_facts_period_end'), 'capital_allocation_facts', ['period_end'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_capital_allocation_facts_period_end'), table_name='capital_allocation_facts')
    op.drop_index(op.f('ix_capital_allocation_facts_company_entity_id'), table_name='capital_allocation_facts')
    op.drop_table('capital_allocation_facts')
    # ### end Alembic commands ###

    # Postgres cannot drop enum values — a value once added stays valid
    # forever (or requires rebuilding the type, which risks any row still
    # using it). No-op here is the accepted asymmetry of additive-only
    # native enums, not an oversight. SQLite needed nothing on the way up,
    # so there's nothing to reverse on the way down either.
