"""Phase 11: UK persons with significant control (Companies House)

Revision ID: 8224e63bf9e8
Revises: b2365ae25799
Create Date: 2026-09-14 00:36:01.813539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8224e63bf9e8'
down_revision: Union[str, Sequence[str], None] = 'b2365ae25799'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # identifier_type gains UK_COMPANY_NUMBER for Phase 11. Only Postgres
    # needs anything done here — same reasoning as every prior enum
    # widening in this project (e.g. 60f668c9c433, b2365ae25799): SQLite's
    # bare VARCHAR column has no DB-level enum constraint to widen. The
    # autogenerated `op.alter_column(...type_=sa.Enum(...))` below was
    # removed — it was Alembic incorrectly diffing the introspected
    # VARCHAR against the Python model's Enum type, not a real schema
    # change needed on SQLite.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE identifier_type ADD VALUE IF NOT EXISTS 'UK_COMPANY_NUMBER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uk_persons_with_significant_control',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('psc_entity_id', sa.Uuid(), nullable=True),
    sa.Column('psc_name', sa.String(length=512), nullable=False),
    sa.Column('psc_kind', sa.String(length=64), nullable=False),
    sa.Column('natures_of_control', sa.JSON(), nullable=False),
    sa.Column('notified_on', sa.Date(), nullable=False),
    sa.Column('ceased_on', sa.Date(), nullable=True),
    sa.Column('country_of_residence', sa.String(length=128), nullable=True),
    sa.Column('nationality', sa.String(length=128), nullable=True),
    sa.Column('companies_house_psc_link', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['psc_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('companies_house_psc_link')
    )
    op.create_index(op.f('ix_uk_persons_with_significant_control_company_entity_id'), 'uk_persons_with_significant_control', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_uk_persons_with_significant_control_notified_on'), 'uk_persons_with_significant_control', ['notified_on'], unique=False)
    op.create_index(op.f('ix_uk_persons_with_significant_control_psc_entity_id'), 'uk_persons_with_significant_control', ['psc_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uk_persons_with_significant_control_psc_entity_id'), table_name='uk_persons_with_significant_control')
    op.drop_index(op.f('ix_uk_persons_with_significant_control_notified_on'), table_name='uk_persons_with_significant_control')
    op.drop_index(op.f('ix_uk_persons_with_significant_control_company_entity_id'), table_name='uk_persons_with_significant_control')
    op.drop_table('uk_persons_with_significant_control')
    # ### end Alembic commands ###

    # Postgres cannot drop enum values once added — no-op here, same
    # accepted asymmetry as every prior enum-widening downgrade in this
    # project. SQLite needed nothing on the way up either.
