"""Phase 14: Finnhub analyst recommendation trends

Revision ID: 9b1597dd0780
Revises: 079b7e248177
Create Date: 2026-09-14 02:51:24.969021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b1597dd0780'
down_revision: Union[str, Sequence[str], None] = '079b7e248177'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_recommendation_trends',
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('strong_buy', sa.Integer(), nullable=False),
    sa.Column('buy', sa.Integer(), nullable=False),
    sa.Column('hold', sa.Integer(), nullable=False),
    sa.Column('sell', sa.Integer(), nullable=False),
    sa.Column('strong_sell', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_entity_id', 'period', name='uq_analyst_recommendation_trend')
    )
    op.create_index(op.f('ix_analyst_recommendation_trends_company_entity_id'), 'analyst_recommendation_trends', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_analyst_recommendation_trends_period'), 'analyst_recommendation_trends', ['period'], unique=False)
    op.create_index(op.f('ix_analyst_recommendation_trends_ticker'), 'analyst_recommendation_trends', ['ticker'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed, same stale VARCHAR-vs-Enum
    # noise as every prior migration since 8224e63bf9e8. No new
    # IdentifierType value is added in this phase.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analyst_recommendation_trends_ticker'), table_name='analyst_recommendation_trends')
    op.drop_index(op.f('ix_analyst_recommendation_trends_period'), table_name='analyst_recommendation_trends')
    op.drop_index(op.f('ix_analyst_recommendation_trends_company_entity_id'), table_name='analyst_recommendation_trends')
    op.drop_table('analyst_recommendation_trends')
    # ### end Alembic commands ###
