"""Phase 15: GDELT news sentiment snapshots

Revision ID: a07929b4c034
Revises: 9b1597dd0780
Create Date: 2026-09-14 10:42:19.503934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a07929b4c034'
down_revision: Union[str, Sequence[str], None] = '9b1597dd0780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sentiment_snapshots',
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('timespan', sa.String(length=16), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('mean_tone', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('tone_distribution', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_snapshots_company_entity_id'), 'news_sentiment_snapshots', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_news_sentiment_snapshots_retrieved_at'), 'news_sentiment_snapshots', ['retrieved_at'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed, same stale VARCHAR-vs-Enum
    # noise as every prior migration since 8224e63bf9e8. No new
    # IdentifierType value is added in this phase.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiment_snapshots_retrieved_at'), table_name='news_sentiment_snapshots')
    op.drop_index(op.f('ix_news_sentiment_snapshots_company_entity_id'), table_name='news_sentiment_snapshots')
    op.drop_table('news_sentiment_snapshots')
    # ### end Alembic commands ###
