"""Phase 10: short interest snapshots (FINRA)

Revision ID: b2365ae25799
Revises: 00f725b1dccc
Create Date: 2026-09-13 22:14:53.791678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2365ae25799'
down_revision: Union[str, Sequence[str], None] = '00f725b1dccc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # event_type gains SHORT_INTEREST_CHANGE for Phase 10. Only Postgres
    # needs anything done here — see the identical note in
    # 60f668c9c433_capital_allocation_facts_new_event_types.py: SQLite's
    # bare VARCHAR column has no DB-level enum constraint to widen.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TYPE event_type ADD VALUE IF NOT EXISTS 'SHORT_INTEREST_CHANGE'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('short_interest_snapshots',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('current_short_position', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('previous_short_position', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('change_percent', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('change_quantity', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('average_daily_volume', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('days_to_cover', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exchange_code', sa.String(length=16), nullable=True),
    sa.Column('market_class_code', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_short_interest_snapshots_company_entity_id'), 'short_interest_snapshots', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_short_interest_snapshots_settlement_date'), 'short_interest_snapshots', ['settlement_date'], unique=False)
    op.create_index(op.f('ix_short_interest_snapshots_ticker'), 'short_interest_snapshots', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_interest_snapshots_ticker'), table_name='short_interest_snapshots')
    op.drop_index(op.f('ix_short_interest_snapshots_settlement_date'), table_name='short_interest_snapshots')
    op.drop_index(op.f('ix_short_interest_snapshots_company_entity_id'), table_name='short_interest_snapshots')
    op.drop_table('short_interest_snapshots')
    # ### end Alembic commands ###

    # Postgres cannot drop enum values once added — no-op here, same
    # accepted asymmetry as 60f668c9c433's downgrade. SQLite needed
    # nothing on the way up either.
