"""Phase 13: daily price bars for backtesting

Revision ID: b411ead20d94
Revises: dbdbcb9ea12e
Create Date: 2026-09-14 02:22:16.369293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b411ead20d94'
down_revision: Union[str, Sequence[str], None] = 'dbdbcb9ea12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_entity_id', 'trade_date', name='uq_price_bar_company_date')
    )
    op.create_index(op.f('ix_price_bars_company_entity_id'), 'price_bars', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_price_bars_ticker'), 'price_bars', ['ticker'], unique=False)
    op.create_index(op.f('ix_price_bars_trade_date'), 'price_bars', ['trade_date'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed, same stale VARCHAR-vs-Enum
    # noise as every prior migration since 8224e63bf9e8. No new
    # IdentifierType value is added in this phase.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_bars_trade_date'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_ticker'), table_name='price_bars')
    op.drop_index(op.f('ix_price_bars_company_entity_id'), table_name='price_bars')
    op.drop_table('price_bars')
    # ### end Alembic commands ###
