"""phase16_alert_webhook_delivery

Revision ID: bac667b20089
Revises: a07929b4c034
Create Date: 2026-09-14 10:53:22.869042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac667b20089'
down_revision: Union[str, Sequence[str], None] = 'a07929b4c034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('webhook_url', sa.String(length=2048), nullable=True))
    op.add_column(
        'alert_rules',
        sa.Column(
            'webhook_format',
            sa.Enum('GENERIC', 'SLACK', name='webhook_format'),
            nullable=False,
            server_default='GENERIC',
        ),
    )
    op.add_column(
        'alerts',
        sa.Column('delivery_attempted', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'alerts',
        sa.Column('delivery_succeeded', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column('alerts', sa.Column('delivery_error', sa.Text(), nullable=True))
    # NOTE: not a real schema change — SQLite's Enum column has no DB-level
    # CHECK constraint (bare VARCHAR), so autogenerate always flags this as
    # a spurious type diff on every migration. See prior migrations for the
    # same note. No-op here, left out intentionally.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'delivery_error')
    op.drop_column('alerts', 'delivery_succeeded')
    op.drop_column('alerts', 'delivery_attempted')
    op.drop_column('alert_rules', 'webhook_format')
    op.drop_column('alert_rules', 'webhook_url')
    # ### end Alembic commands ###
