"""fundamental reports (revenue, earnings, margins)

Revision ID: cb731d1c2a2d
Revises: 60f668c9c433
Create Date: 2026-09-13 21:40:56.020075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb731d1c2a2d'
down_revision: Union[str, Sequence[str], None] = '60f668c9c433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fundamental_reports',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.Enum('QUARTER', 'FISCAL_YEAR', name='fundamental_period_type'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=8), nullable=True),
    sa.Column('revenue_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('net_income_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('eps_diluted', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_profit_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('operating_income_usd', sa.Numeric(precision=24, scale=2), nullable=True),
    sa.Column('gross_margin_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('operating_margin_pct', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('filing_form_type', sa.String(length=16), nullable=True),
    sa.Column('filing_accession', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_fundamental_reports_company_entity_id'), 'fundamental_reports', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_fundamental_reports_period_end'), 'fundamental_reports', ['period_end'], unique=False)
    op.create_index(op.f('ix_fundamental_reports_period_type'), 'fundamental_reports', ['period_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamental_reports_period_type'), table_name='fundamental_reports')
    op.drop_index(op.f('ix_fundamental_reports_period_end'), table_name='fundamental_reports')
    op.drop_index(op.f('ix_fundamental_reports_company_entity_id'), table_name='fundamental_reports')
    op.drop_table('fundamental_reports')
    # ### end Alembic commands ###
