"""Phase 12: crypto treasury movements and guidance disclosures

Revision ID: d448a1c970e2
Revises: 8224e63bf9e8
Create Date: 2026-09-14 00:52:23.988642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd448a1c970e2'
down_revision: Union[str, Sequence[str], None] = '8224e63bf9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_treasury_movements',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('wallet_entity_id', sa.Uuid(), nullable=False),
    sa.Column('chain', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=30, scale=8), nullable=False),
    sa.Column('block_height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['wallet_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('chain', 'tx_hash', 'address', name='uq_crypto_treasury_movement')
    )
    op.create_index(op.f('ix_crypto_treasury_movements_address'), 'crypto_treasury_movements', ['address'], unique=False)
    op.create_index(op.f('ix_crypto_treasury_movements_chain'), 'crypto_treasury_movements', ['chain'], unique=False)
    op.create_index(op.f('ix_crypto_treasury_movements_wallet_entity_id'), 'crypto_treasury_movements', ['wallet_entity_id'], unique=False)
    op.create_table('guidance_disclosures',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('item_codes', sa.String(length=64), nullable=False),
    sa.Column('filing_form_type', sa.String(length=16), nullable=False),
    sa.Column('filing_accession', sa.String(length=32), nullable=False),
    sa.Column('primary_document_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['company_entity_id'], ['companies.entity_id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_guidance_disclosures_company_entity_id'), 'guidance_disclosures', ['company_entity_id'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed. No new IdentifierType value
    # is added in this phase (CRYPTO_WALLET/WALLET_ADDRESS already
    # existed); this was Alembic re-diffing the same stale VARCHAR-vs-Enum
    # comparison noted in 8224e63bf9e8, not a real schema change.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guidance_disclosures_company_entity_id'), table_name='guidance_disclosures')
    op.drop_table('guidance_disclosures')
    op.drop_index(op.f('ix_crypto_treasury_movements_wallet_entity_id'), table_name='crypto_treasury_movements')
    op.drop_index(op.f('ix_crypto_treasury_movements_chain'), table_name='crypto_treasury_movements')
    op.drop_index(op.f('ix_crypto_treasury_movements_address'), table_name='crypto_treasury_movements')
    op.drop_table('crypto_treasury_movements')
    # ### end Alembic commands ###
