"""Phase 13: short-interest convergence family and alerting layer

Revision ID: dbdbcb9ea12e
Revises: d448a1c970e2
Create Date: 2026-09-14 01:20:11.805641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbdbcb9ea12e'
down_revision: Union[str, Sequence[str], None] = 'd448a1c970e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('rule_type', sa.Enum('INSIDER_CONVICTION_THRESHOLD', 'INSTITUTIONAL_ACCUMULATION_THRESHOLD', 'SHORT_INTEREST_ACCELERATION_THRESHOLD', 'CONVERGENCE_LABEL', name='alert_rule_type'), nullable=False),
    sa.Column('min_composite_score', sa.Float(), nullable=True),
    sa.Column('convergence_labels', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alerts',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('company_entity_id', sa.Uuid(), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('signal_summary', sa.Text(), nullable=False),
    sa.Column('source_event_ids', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'company_entity_id', 'alert_date', name='uq_alert_per_rule_company_date')
    )
    op.create_index(op.f('ix_alerts_alert_date'), 'alerts', ['alert_date'], unique=False)
    op.create_index(op.f('ix_alerts_company_entity_id'), 'alerts', ['company_entity_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    # Autogenerate also proposed `op.alter_column('entity_identifiers',
    # 'identifier_type', ...)` here — removed, same stale VARCHAR-vs-Enum
    # noise as 8224e63bf9e8 and d448a1c970e2. No new IdentifierType value
    # is added in this phase.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_company_entity_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_date'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
